### ISSUE TITLE
Include static pages 

### ISSUE THREAD

**Issue by 153** [lily-fyi/bubblebbs#38]
e.g. 

- faq / rules (/faq/)
- formatting (/faq/#formatting) 
- irc (/irc/)
- contact moderation (/contact/) 
- other (/other/ or /pages/other) 

especially after styleswitcher is implemented

**Comment by lily-mayfield** [comment]
Cool idea!

**Comment by lily-mayfield** [comment]
I could use the markdown system we have now for page building!
